# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: sort-simple-yaml
  - repo: local
    hooks:
      - id: format
        name: Format
        entry: uvx ruff format
        args: [--force-exclude, --fix]
        language: python
        types: [python]
        require_serial: true
      - id: lint
        name: Lint
        entry: uvx ruff check
        args: [--force-exclude, --fix]
        language: python
        types: [python]
        require_serial: true
      - id: types
        name: Types
        entry: uv run ty check
        language: python
        types: [python]
        pass_filenames: false
