[project]
name = 'connect_four'
version = '0.1.0'
description = 'This Connect Four game has a very simple AI and CLI which allows humans to play against each other or against the AI.'
readme = 'README.md'
authors = [{ name = 'Tyler BoddySpargo', email = 'muyleche@gmail.com' }]
maintainers = [{ name = 'Tyler BoddySpargo', email = 'muyleche@gmail.com' }]
license = { file = 'LICENSE' }
keywords = ['connect four', 'game', 'cli', 'boddyspargo']
classifiers = [
    'Development Status :: 4 - Beta',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Topic :: Games/Entertainment :: Puzzle Games',
]
requires-python = '>=3.10'
dependencies = [
    "codetiming",
    "pre-commit>=4.5.1",
]


[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.4",
    "ty>=0.0.19",
]

[project.scripts]
c4 = 'connect_four.main:main'
t4 = 'connect_four.main:experiment'

[project.urls]
homepage = 'https://github.com/tboddyspargo/connect_four_py'
repository = 'https://github.com/tboddyspargo/connect_four_py.git'

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"


[tool.ruff]
line-length = 120
target-version = "py39"
select = ["ALL"]
extend-exclude = ["*.egg-info", ".*"]
ignore = [
    'D212',
    'W191',
    'E111',
    'E114',
    'E117',
    'D206',
    'D300',
    'Q000',
    'Q001',
    'Q002',
    'Q003',
    'COM812',
    'COM819',
    'ISC001',
    'ISC002',
]

[[tool.ty.overrides]]
include = ["tests/**", "**/test_*.py"]

[tool.ty.overrides.rules]
possibly-unresolved-reference = "warn"

[tool.ty.overrides.analysis]
respect-type-ignore-comments = true
